spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minicampus
    driver-class-name: com.mysql.jdbc.Driver
    username: minicampus_user
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: fightboolo@gmail.com
    password: sgowvbssikynsllv
    properties:
      mail:
        smtp:
          starttls:
            enable: true


